version:  '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped
    
  agent:
    image: jenkins/ssh-agent:jdk11
    container_name: jenkins-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa YOUR_PUBLIC_KEY
    volumes:
      - jenkins_agent_home:/home/jenkins
    restart: unless-stopped

volumes:
  jenkins_home:
  jenkins_agent_home:
 