FROM  python:3.10-slim

# Install essential tools
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    curl \
    git \
    zip \
    unzip \
    xvfb \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libxss1 \
    libxtst6 \
    xdg-utils \
    libgbm1 \
    && rm -rf /var/lib/apt/lists/*

# Install Allure
RUN curl -o allure-2.22.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.22.0/allure-2.22.0.tgz \
    && tar -zxvf allure-2.22.0.tgz -C /opt/ \
    && ln -s /opt/allure-2.22.0/bin/allure /usr/bin/allure \
    && rm allure-2.22.0.tgz

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install Playwright browsers
RUN playwright install chromium firefox webkit

# Set display for non-headless browser tests
ENV DISPLAY=:99
 