name:  Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        test-group: [smoke, search, cart, checkout]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
    
    - name: Run tests
      run: |
        python run_tests.py --browser ${{ matrix.browser }} --headless --markers ${{ matrix.test-group }} --allure
      env:
        BASE_URL: https://automationexercise.com
        ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'staging' || 'dev' }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.browser }}-${{ matrix.test-group }}
        path: |
          allure-results/
          screenshots/
          videos/
          logs/
    
    - name: Generate Allure Report
      if: always()
      run: |
        pip install allure-commandline
        allure generate allure-results --clean -o allure-report
    
    - name: Publish Allure Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report-${{ matrix.browser }}-${{ matrix.test-group }}
        path: allure-report/
 